CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255) not null,
    last_name       VARCHAR(255) not null,
    email           VARCHAR(255) not null,
    password        VARCHAR(255) not null,
    profile_picture VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);
insert into users (first_name, last_name, email, password, profile_picture) values
('admin','admin','admin','$2a$10$DeBQKi0/OBbxynOlX3CdquTrk1n0VmY0oqpn6SVY47CtLiYntxCMq',null)