server:
  port: 9898

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/greenhouse
    username: postgres
    password: alisher2003
    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  #Mail sender
  mail:
    host: post.mail.kz
    username: nobd@edu.kz
    password: qaz123WSX#!
    port: 587
    from: nobd@edu.kz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          ssl:
            enable: false
            trust: "*"
        debug: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/