server:
  port: 9898

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://34.125.1.104:5432/greenhouse
    username: postgres
    password: postgres
    hikari:
      max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: none
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
  #Mail sender
  mail:
    host: smtp.gmail.com
    port: 587
    username: greenhousedevteam@gmail.com
    password: fnrzyefeplvlumjh
    protocol: smtp
    from: greenhousedevteam@gmail.com
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://34.125.138.217:8767/eureka/