server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://34.125.1.104:5432/greenhouse
    hikari:
      max-lifetime: 1800000
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://34.125.138.217:9898
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1
        - id: smart-greenhouse
          uri: http://34.125.138.217:8082
          predicates:
            - Path=/gateway/smart-greenhouse/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1
        - id: file-store
          uri: http://34.125.138.217:8890
          predicates:
            - Path=/gateway/file-store/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://34.125.138.217:8767/eureka/