server:
  port: 8090
  servlet:
    context-path: /greenhouse-gateway

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9898
          predicates:
            - Path=/gateway/auth/**
          filters:
            - StripPrefix=1
        - id: smart-greenhouse-service
          uri: http://localhost:8080
          predicates:
            - Path=/gateway/smart-greenhouse/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8767/eureka/