server:
  port: 8767

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8767/eureka/
spring:
  application:
    name: eureka
