server:
  port: 8082
  servlet:
    context-path: /smart-greenhouse
spring:
  application:
    name: smart-greenhouse
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://34.125.1.104:5432/greenhouse
    hikari:
      max-lifetime: 1800000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  liquibase:
    change-log: db/changeLog.xml
  jackson:
    serialization:
      fail-on-empty-beans: false
jwt:
   secret: SECRET


eureka:
  client:
    service-url:
      defaultZone: http://34.125.138.217:8767/eureka/

firebase:
  key: AAAAeqkAQBU:APA91bEUJ5BcaMOsMeyRz9cl1q6jzfwxQVCzhWyyWVFuW-2uneFBvGBVphAtLMfL1jcCtc8OgxLSznSeE8trNvCetHSRw2gnzgJYV86kEgSxwtQsC0FH5wAOKkXC5DqelvXqXmbUYa6n
  url: https://fcm.googleapis.com/fcm/send