server:
  port: 8890
  servlet:
    context-path: /file-store
spring:
  application:
    name: file-storage
  data:
    mongodb:
      host: 34.125.251.28
      port: 9876
      database: mydatabase
      authentication-database: mydatabase
      username: myuser
      password: mypassword
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB


eureka:
  client:
    service-url:
      defaultZone: http://34.125.138.217:8767/eureka/